import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const montserrat = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-montserrat",
  weight: "100 900",
});

const dancingScript = localFont({
  src: "./fonts/DancingScript-VariableFont_wght.ttf",
  variable: "--font-dancing-script",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dancingScript.variable} ${montserrat.variable} antialiased font-[family-name:var(--font-montserrat)] bg-pagebackground`}
      >
        <header className=" p-4 w-full flex text-white flex-row place-content-between bg-gradient-to-r from-gradientstart to-gradientend">
          <h1 className="text-lg font-bold">Placeholder Navbar</h1>
          <Link href="/login/" className="border py-2 px-6 rounded-full">
            placeholder login button
          </Link>
        </header>

        <main className="">
          {children}
          </main>

        <footer>
          <p>placeholder footer</p>
        </footer>
      </body>
    </html>
  );
}
